version: '3.7'
services:
 config-server:
  container_name: config-server
  image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
#  hostname: config-server
  volumes:
   - "./docker-logs:/workspace/config-server/logs"
  ports:
   - "5006:5006"
   - "8888:8888"
  networks: 
   - ${GLOBAL_NETWORK:-services}
 twitter-to-kafka-service:
  image: ${GROUP_ID}/twitter.to.kafka.service:${SERVICE_VERSION:-latest}
  ports:
   - "5005:5005"
  volumes:
   - "./docker-logs:/workspace/twitter-to-kafka-service/logs"
   - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
  user: root  
  entrypoint: ["check-config-server-started.sh"]
  environment:
   - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092"
   - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
   - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
  depends_on:
      - config-server
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
  networks:
   - ${GLOBAL_NETWORK:-services}
 
 
   